
spring:
  profiles: pro

  #ssdb config
  ssdb:
    master:
      host: 192.168.168.1
      port: 8888
    slave:
      host: 192.168.168.2
      port: 8888
    timeout: 3000
    pool:
      maxIdle: 8
      minIdle: 0
      maxActive: 10
      maxWait: -1
      whenExhaustedAction: 1
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: -1

