
spring:
  profiles: dev

  #ssdb config
  ssdb:
    master:
      host: 10.12.40.37
      port: 8888
    slave:
      host: 10.12.40.25
      port: 8888
    timeout: 3000
    pool:
      maxIdle: 8
      minIdle: 0
      maxActive: 10
      maxWait: -1
      whenExhaustedAction: 1
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: -1

